# Generated by hand to match 0001_initial.py's style (no local Django to autogenerate with).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(
                choices=[('farmer', 'Farmer'), ('expert', 'Expert'), ('consumer', 'Consumer')],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=80)),
                ('quantity', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=120)),
                ('budget', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True, max_length=800)),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProduceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=80)),
                ('quantity', models.CharField(max_length=40)),
                ('price', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, max_length=800)),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
